### PR TITLE
Add Arabic language

### LINKED ISSUE #55: Arabic language support
Hello.

I noted that the Arabic isn't supported yet. so I'm willing to add it. Any advice?

### PR DESCRIPTION
**Pull request by adhaamehab**
This PR adds _Arabic_  to the list of supported languages.

### Example

```python
from summa.keywords import keywords
from summa.summarizer import summarize

text = """رحلت عن عالمنا إيفلين بيريزين، المرأة التي اخترعت ما يعتبره الكثيرون أول معالجة نصوص إلكترونية، عن 93 عاما.
وأطلقت بيريزين على اختراعها اسم "سكرتيرة البيانات" حين روجته شركتها عام 1971.
وطورت شركتها "ريداكترون" بحيث ارتفع عدد مستخدميها من تسعة أشخاص ليصل 500 واعتبرتها مجلة "بيزنس ويك" واحدة من كبار سيدات الأعمال في الولايات المتحدة عام 1976.
وكانت قد صممت واحدا من أنظمة حجز الطيران عن طريق الكمبيوتر، واختبرته شركة يونايتد إيرلاينز عام 1962.
وأفاد متحف تاريخ الحاسوب أن النظام عمل لمدة 11 عاما بدون أي خلل في نظامه المركزي.
وطورت أنظمة أخرى، منها نظام مصرفي آلي، وأنظمة تحسب عمليات الرهان على سباق الخيول.
وقالت بيريزين في مقابلة أجريت معها عام 2015 إنها اقامت مشروعا خاصا بها في منتصف ستينيات القرن الماضي بعد أن استنتجت أن فرصها في النجاح كموظفة تبقى محدودة.
وقالت إنها فكرت في البداية بتطوير حاسب إلكتروني لعد النقود لكنها في النهاية استقرت على معالجة النصوص الإلكترونية.
وكان الجهاز الذي طورته بارتفاع متر وفيه لوحة مفاتيح ويوجه إلكترونيا ويتبعه طابعة، ويستطيع تسجيل ما يطبعه المستخدم من أجل التحرير في وقتت لاحق.
وقد افتقر الجهاز الأولي للشاشة وما لبث أن ظهر منافسون له، مثل جهاز ليكسيترون، الذي كان يملك شاشة.
ثم أصبح جهاز بيريزين بدوره مجهزا بشاشة.
وقد ازدهرت الشركة وزاد الطلب على منتجاتها، لولا الركود الاقتصادي في السبعينيات الذي اضطر العملاء لاستئجار الآلات بدلا من شرائها، واضطرت بيريزين في النهاية إلى بيع الشركة.
وقد رحلت في الثامن من ديسمبر/كانون أول في مانهاتن بعد أن رفضت تلقي العلاج من السرطان."""
```

```python
summarize(text, language='arabic', ratio=0.5)
```
```رحلت عن عالمنا إيفلين بيريزين، المرأة التي اخترعت ما يعتبره الكثيرون أول معالجة نصوص إلكترونية، عن 93 عاما.
وأطلقت بيريزين على اختراعها اسم "سكرتيرة البيانات" حين روجته شركتها عام 1971.
وطورت شركتها "ريداكترون" بحيث ارتفع عدد مستخدميها من تسعة أشخاص ليصل 500 واعتبرتها مجلة "بيزنس ويك" واحدة من كبار سيدات الأعمال في الولايات المتحدة عام 1976.
وكانت قد صممت واحدا من أنظمة حجز الطيران عن طريق الكمبيوتر، واختبرته شركة يونايتد إيرلاينز عام 1962.
وقالت بيريزين في مقابلة أجريت معها عام 2015 إنها اقامت مشروعا خاصا بها في منتصف ستينيات القرن الماضي بعد أن استنتجت أن فرصها في النجاح كموظفة تبقى محدودة.
وقد ازدهرت الشركة وزاد الطلب على منتجاتها، لولا الركود الاقتصادي في السبعينيات الذي اضطر العملاء لاستئجار الآلات بدلا من شرائها، واضطرت بيريزين في النهاية إلى بيع الشركة.
```
```python
keywords(text, language='arabic')
```
```
['عاما', 'شركتها عام', 'شركة', 'الشركة', 'الجهاز', 'جهاز', 'بيريزين', 'وقد', 'أنظمة', 'وأنظمة', 'أول', 'وطورت', 'طورته', 'الأولي للشاشة', 'إلكترونية', 'الإلكترونية', 'إلكترونيا', 'وقالت', 'إنها', 'عمليات', 'شاشة', 'بشاشة', 'تلقي', 'سيدات', 'النظام عمل', 'ستينيات القرن', 'اسم', 'سكرتيرة', 'العملاء لاستئجار الآلات', 'نظامه', 'نظام', 'بتطوير', 'النقود', 'واحدة', 'واحدا', 'أشخاص']
```
Fix #55

### CODE REVIEW

**Comment by adhaamehab** [comment]
@fbarrios Can you review this?

**Comment by fbarrios** [comment]
Hi! Sorry for having this parked. We're on holidays until next week, then I'll gladly review this.

**Comment by adhaamehab** [comment]
No problem at all. Happy holidays

**Comment by fedelopez77** [comment]
Hello @adhaamehab!

Thank you for your contribution! Looks great.
Could you please add at least one test for this and then we merge it?

Thanks!

**Comment by adhaamehab** [comment]
Hi @fedelopez77 
Just added a test. Please check.
Thanks!

**Comment by fbarrios** [comment]
@adhaamehab amazing! Thank you for your contribution.

**Pull request merged**
